### ISSUE TITLE
普通邮件示例发送失败

### ISSUE THREAD

**Issue by yongfenghao** [denger/sendcloud4j#10]
SendCloud webapi = SendCloud.createWebApi(apiUser, apiKey);
		Email email = Email.general().from("support@jk.com").fromName("jk Support").html("<b>Hello World!</b>").subject("find password").to("523699657@qq.com");
		Result result = webapi.mail().send(email);
		System.out.println(result.isSuccess());
		System.out.println(result.getStatusCode());
		System.out.println(result.getMessage());
------------以下是输出
false
40908
邮件内容和邮件模板匹配不通过. reason:unequal content

问题：调用的普通邮件发送方法，但是却报模板不匹配的错误，麻烦确认下

**Comment by denger** [comment]
sendcloud 无论是普通还是模板邮件，都需要预先配置好模板，两者的区别在于普通邮件不支持变量替换且是固定内容。

**Comment by yongfenghao** [comment]
谢谢回复，那其实必须要 Email.template("template_order_customer") 这种方式调用了
