### ISSUE TITLE
期待增加代理发送

### ISSUE THREAD

**Issue by freezhan** [denger/sendcloud4j#12]

**Comment by denger** [comment]
已支持。使用 `0.0.5` 版本即可，详情可以看 [Readme](https://github.com/denger/sendcloud4j)。

**Comment by freezhan** [comment]
看了下代码，感谢及时添加，期待 maven 库中的版本也早日更新。

比官方的 SDK 看着更舒服

**Comment by denger** [comment]
已发布。 http://central.maven.org/maven2/io/jstack/sendcloud4j/
