### ISSUE TITLE
通过邮件模板发送，一封邮件如何批量发送给多个人

### ISSUE THREAD

**Issue by freezhan** [denger/sendcloud4j#13]
看 sendcloud 官方文档
1. 普通邮件可以一封邮件指定多个收件人
2. 模板邮件想要批量发送，只能通过地址列表实现，或者一封邮件的内容复制多份
[sendcloud 模板发送请求示例](http://sendcloud.sohu.com/doc/email_v2/send_email/#_2)

`curl -d 'apiUser=***&apiKey=***&from=test@test.com&fromName=liubida&subject=测试&replyTo=reply@test.com&templateInvokeName=ifaxin_bill' --data-urlencode 'xsmtpapi={"to": ["ben@ifaxin.com", "joe@ifaxin.com"],"sub":{"%name%": ["Ben", "Joe"],"%money%":[288, 288]}}&headers={"header": "value", "header": "value"}' http://api.sendcloud.net/apiv2/mail/sendtemplate`

假设内容都是填充

> name: Ben, money: 288

``` json
{
    "sub": {
        "%name%": [
            "Ben", 
            "Ben"
        ], 
        "%money%": [
            288, 
            288
        ]
    }
}
```

收信人有多个

> testA@tester.com;testB@tester.com

多一个收信人就多复制一遍同样的内容感觉很恶心, 同时每次发邮件之前维护地址列表也体验很不好。

我知道可以在本地渲染模板，然后按照普通模式发送出去，sendcloud 会自动匹配已经验证过的模板。
不过这样就要自己多维护一段 html 相关的代码了

可否直接这样发送达到我想要的目的:

``` java
        SendCloud webapi = SendCloud.createWebApi(apiUser, apiKey);

        Email email = Email.template("test_template_name")
                .from("XXX@test.com")
                .fromName("test from name")
                .substitutionVars(Substitution.sub()
                        .set("name", "Ben")
                        .set("money", "288"))
                .to(new String[]{"testA@tester.com", "testB@tester.com"});

        Result result = webapi.mail().send(email);
        System.out.println(result.toString());
```

目前是报这样的错误:

> {"result":false,"statusCode":40817,"message":"xsmtpapi解析错误. sub[%name%] 的列表长度和 to 的个数不相等","info":{}}

**Comment by denger** [comment]
`substitutionVars()` 支持使用 `Substitution.SubGroup`，具体可以参考：https://github.com/denger/sendcloud4j/blob/master/src/test/java/io/jstack/sendcloud4j/mail/SubstitutionTest.java  函数： `testSubGroups`

**Comment by denger** [comment]
目前针对你这个需求的做法是，生成一个 `Substitution.sub()` ，然后使用 `Substitution.SubGroup`  来 `add` 多次（与收件人数量一致）。

你的这个建议可以考虑，如果只写了一份变量但写了多个收件人，可以支持批量发送。

**Comment by freezhan** [comment]
感谢~
