### ISSUE TITLE
与本地log4j冲突

### ISSUE THREAD

**Issue by RyanPro** [denger/sendcloud4j#18]
会覆盖本地log4j的配置。导致本地日志配置不可用

**Comment by RyanPro** [comment]
建议将工程里的log4j.xml文件删掉

**Comment by denger** [comment]
你是如何引用的？ 如果是maven jar 依赖的话并不会有 log4j.xml 。 且 log4j.xml 是在 test 目录下的，通常 maven 发布打包都会排除 test 目录。

**Comment by RyanPro** [comment]
我猜想是因为引用了logback-classic的jar包导致的。因为我本地也引用了log4j。具体看这篇文章
http://magician8421.iteye.com/blog/2068425

**Comment by RyanPro** [comment]
我这边排除依赖以后，日志正常了
![qq 20170228092129](https://cloud.githubusercontent.com/assets/8781128/23387438/8142fb72-fd97-11e6-8c3b-0f453d4ae475.jpg)

**Comment by denger** [comment]
明白了。我将 log 相关的依赖 jar，增加一个 scope 为 test，避免传递依赖。

**Comment by RyanPro** [comment]
^_^
