### ISSUE TITLE
模板邮件发送，模板变量替换失败

### ISSUE THREAD

**Issue by rechal-liu** [denger/sendcloud4j#19]
使用模板的示例代码，邮件发送成功，但是变量没有被替换 ，会是什么原因呢？
`Email email = Email.template("activeAccount")//我的模板名称
    .from("support@jstack.io")
    .fromName("JStack Support")
    .substitutionVars(Substitution.sub()   
            .set("content", "iPhone 6S")
            .set("date", "20170703").
            .set("email", "2377@qq.com"))
    .attachment(new File("att.png"))      // 添加附件 (File or byte[])成功
    .to("denger.it@gmail.com");`

我的模板:
![image](https://cloud.githubusercontent.com/assets/12309682/23655511/354cca7a-0370-11e7-98bd-b05b35200d0f.png)

 其中set(key,value) 我试了 {{content}} 、content 、都不行 ，发送的内容变量没有被替换掉。

**Comment by rechal-liu** [comment]
附上我的代码 
`Email<?> email = Email.template("activeAccount")//我的模板名称`
` .from("hongshiyun@arcvideo.cn")`
`.fromName("JStack Support")`
`.substitutionVars(Substitution.sub() // 模板变量替换`
`.set("{{content}}",  "[iPhone 6S]")  // .set("content",  "[iPhone 6S]")`
`.set("{{date}}", "[2017-03-07]") `
`.set("{{email}}", "[2322@qq.com]"))	`
`.to("237738572@qq.com");`
`Result result = webapi.mail().send(email);`
`System.out.println(result.isSuccess());      //API 请求是否成功`
`System.out.println(result.getStatusCode());  //API 返回码`

**Comment by denger** [comment]
1. 代码中是不需要写 {{}}，只需要变量名即可。
2. 请看下你的 sendcloud 后台模板是如何配置的？ 是写的 %name% 吗？

**Comment by rechal-liu** [comment]
一楼的图 是我的模板配置，模板内我配置的是{{name}} ; 这个模板是之前很久前创建的,用原始的HTTP 请求是可以发送成功且替换成功的，看到你分享的SDK，用你简洁的代码试了下，结果替换不了。
 我看到你 Substitution.sub().set 的源码, 一定要%name% 设定的变量才会被替换是吗？

**Comment by denger** [comment]
哦？用 {} 的做变量，之前印象中他只支持使用％的方式。可以改下模板使用%试试？

如果确定该问题的话我再升级一下该逻辑。

**Comment by rechal-liu** [comment]
%name% 测试OK;  {{}}的写法是sendCloud 很早以前的一种写法。目前升级到API2.0 后估计都是%%写法了。作者分享的很好，我修改模板后使用很方便，感谢作者。
