### ISSUE TITLE
Readme中的 maven的地址是有问题的

### ISSUE THREAD

**Issue by Mylog** [denger/sendcloud4j#5]
<groupId>io.jstack</groupId>
        <artifactId>sendcloud4j</artifactId>
        <version>0.0.4</version>
        </dependency>

**Comment by denger** [comment]
什么问题？

**Comment by Mylog** [comment]
<dependency>
    <groupId>io.jstack</groupId>
    <artifactId>sendcloud4j</artifactId>
    <version>0.0.4</version>
</dependency>
