### ISSUE TITLE
如果模板里出现2个相同参数的变量的话 好像替换不掉

### ISSUE THREAD

**Issue by SuperLv** [denger/sendcloud4j#9]
比如 我模板设置的是 %name%------%name%
代码是
Substitution.sub().set("name", "test")..set("name", "test")
最后邮件里显示的 test----%name%

**Comment by denger** [comment]
我这测试“触发”类型的模板是可以正常替换的，确认一下变量是否**完全**一致？或能告诉我如何重现？
